version: "3"
services:
    api:
        build: ./api
        ports:
            - "49849:80"
        depends_on:
            - db
        environment:
            - ASPNETCORE_ENVIRONMENT="Development"
            - ConnectionStrings__DefaultConnection=Server=db;Database=shuffler;User=sa;Password=QWERTY123!
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "QWERTY123!"
            ACCEPT_EULA: "Y"
        ports:
            - "5433:1433"