version: "3"
services:
    api:
        build: ./api
        ports:
            - "49849:80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "QWERTY123!"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"